global:
  pattern: secure-mcp-code-gateway
  secretLoader:
    disabled: true
  options:
    installPlanApproval: Automatic
    syncPolicy: Automatic
    useCSV: false
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
