clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
    - secure-mcp-code-gateway
    - open-cluster-management
    - vault
    - golang-external-secrets
    - mcp-shared
    - openshift-logging
  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.14
    logging:
      name: cluster-logging
      namespace: openshift-logging
      channel: stable-5.8
      source: redhat-operators
    rhsso-operator:
      name: rhsso-operator
      namespace: mcp-shared
      channel: stable
      source: redhat-operators
  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      chart: acm
      chartVersion: 0.1.*
      argoProject: hub
    cluster-logging-instance:
      name: cluster-logging-instance
      namespace: openshift-gitops
      path: charts/hub/cluster-logging-instance
      argoProject: hub
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      chart: golang-external-secrets
      chartVersion: 0.1.*
      argoProject: hub
    keycloak-sso:
      name: keycloak-sso
      namespace: openshift-gitops
      path: charts/hub/keycloak-sso
      argoProject: mcp-shared
      ignoreDifferences:
        - group: keycloak.org
          jsonPointers:
            - /spec/client/secret
          kind: KeycloakClient
    mcp-gateway:
      name: mcp-gateway
      namespace: openshift-gitops
      path: charts/hub/mcp-gateway
      argoProject: mcp-shared
    mcp-log-analysis-gateway:
      name: mcp-log-analysis-gateway
      namespace: secure-mcp-code-gateway
      path: charts/hub/examples/per-mcp-gateway/mcp-log-analysis-gateway
      argoProject: mcp-shared
    mcp-log-analysis-sandbox:
      name: mcp-log-analysis-sandbox
      namespace: openshift-gitops
      path: charts/hub/mcp-log-analysis-sandbox
      argoProject: mcp-shared
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
      argoProject: hub
  argoProjects:
    - hub
    - mcp-shared
  imperative:
    jobs: []
  sharedValueFiles:
    - /overrides/values-{{ $.Values.global.clusterPlatform }}.yaml
    - /overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml
